### ISSUE TITLE
Facebook shares not loading on phone

### ISSUE THREAD

**Issue by hannamade** [osahyoun/istreetwatch#9]
I'm trying to share on Facebook from the timeline and from the about page, and the shares aren't loading. It just has a loading circle that has an option to cancel but it never loads. Don't know if this is an issue with my phone (safari browser on iPhone 6) but the pages and tweet are loading quickly.

**Comment by andylolz** [comment]
Same (on chrome/android). If I request desktop site on mobile it’s fine.

I wonder if it’s a problem with [the mobile iframe thing](https://github.com/osahyoun/istreetwatch/blob/27f6b08d/app/views/reports/timeline.html.erb#L34)?

**Comment by osahyoun** [comment]
fixed
